# -*- coding: utf-8 -*-
"""Loan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JQVDmwcvIPBMWRDlBXK71j5pRgeu8F6u
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

import plotly.express as px
import plotly.graph_objects as go

file_path="/content/drive/MyDrive/loan.csv"

file_path="/content/drive/MyDrive/loan.csv"

# Load Dataset
df = pd.read_csv(file_path)

# Display First 5 Rows
print(df.head())

# Dataset Information
print(df.info())

# Check Missing Values
print(df.isnull().sum())

selected_columns = [
    'loan_amnt',      # Correct column for LoanAmount
    'term',           # Correct column for LoanTerm
    'int_rate',       # Correct column for InterestRate
    'annual_inc',     # Correct column for Income
    'emp_length',     # Correct column for MonthsEmployed
    'home_ownership', # Correct column for HasMortgage
    'purpose',        # Correct column for LoanPurpose
    'loan_status'     # Correct column for Default
]

df = df[selected_columns].copy()

print("\nMissing Values:")
print(df.isnull().sum())
df.dropna(inplace=True)
# Convert 'term' column to numerical format
df['term'] = df['term'].str.replace(' months', '', regex=False).astype(int)

print("\nAverage Loan Amount:")
print(df['loan_amnt'].mean())

print("\nAverage Annual Income:")
print(df['annual_inc'].mean())

print("\nInterest Rate Statistics:")
print(df['int_rate'].describe())

default_counts = df['loan_status'].value_counts()

plt.figure(figsize=(6,5))
sns.countplot(x='loan_status', data=df)
plt.title("Loan Status Distribution")
plt.show()

print("\nLoan Status Count:")
print(default_counts)

income_default = df.groupby('loan_status')['annual_inc'].mean()
print("\nIncome vs Loan Status:")
print(income_default)
emp_default = df.groupby('loan_status')['emp_length'].mean()
print("\nEmployment Length vs Loan Status:")
print(emp_default)
home_default = pd.crosstab(df['home_ownership'], df['loan_status'])
print("\nHome Ownership vs Default:")
print(home_default)
purpose_default = pd.crosstab(df['purpose'], df['loan_status'])
print("\nPurpose vs Default:")
print(purpose_default)

plt.figure(figsize=(8,5))
sns.scatterplot(x='loan_amnt', y='int_rate', hue='loan_status', data=df)
plt.title("Loan Amount vs Interest Rate")
plt.show()
plt.figure(figsize=(8,5))
sns.scatterplot(x='annual_inc', y='loan_amnt', hue='loan_status', data=df)
plt.title("Income vs Loan Amount")
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df['loan_amnt'], bins=30, kde=True)
plt.title("Loan Amount Distribution")
plt.show()
plt.figure(figsize=(8,5))
sns.histplot(df['annual_inc'], bins=30, kde=True)
plt.title("Annual Income Distribution")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x=df['loan_amnt'])
plt.title("Loan Amount Boxplot")
plt.show()
plt.figure(figsize=(8,5))
sns.boxplot(x=df['annual_inc'])
plt.title("Income Boxplot")
plt.show()

numeric_df = df.select_dtypes(include=np.number)

plt.figure(figsize=(10,6))
sns.heatmap(numeric_df.corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

def classify_risk(rate):
    if rate < 10:
        return "Low Risk"
    elif rate < 20:
        return "Medium Risk"
    else:
        return "High Risk"

df['Risk_Level'] = df['int_rate'].apply(classify_risk)

print("\nRisk Level Counts:")
print(df['Risk_Level'].value_counts())

# Ensure 'term' column is numerical before creating X and y
# This step is included here to make the cell robust against execution order issues,
# as df['term'] should already be int after F3MZ9h2d5nxX runs.
if df['term'].dtype == 'object':
    df['term'] = df['term'].str.replace(' months', '', regex=False).astype(int)

X = df[['annual_inc', 'int_rate', 'term']]
y = df['loan_amnt']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("\nModel Evaluation")
print("----------------------")
print("R2 Score:", r2)
print("MAE:", mae)
print("RMSE:", rmse)

residuals = y_test - y_pred

plt.figure(figsize=(8,5))
sns.scatterplot(x=y_pred, y=residuals)
plt.axhline(y=0, color='red')
plt.title("Residual Plot")
plt.xlabel("Predicted Loan Amount")
plt.ylabel("Residuals")
plt.show()

fig1 = px.scatter(
    df,
    x='Income',
    y='LoanAmount',
    color='Default',
    title='Income vs Loan Amount'
)

fig1.show()
fig2 = px.histogram(
    df,
    x='LoanAmount',
    color='Default',
    title='Loan Amount Distribution'
)

fig2.show()
fig3 = px.box(
    df,
    x='Default',
    y='InterestRate',
    color='Default',
    title='Interest Rate vs Loan Status'
)

fig3.show()
fig4 = px.bar(
    df,
    x='HasMortgage',
    color='Default',
    title='Default Comparison by Home Ownership'
)

fig4.show()